# Generated by Django 4.2.5 on 2023-10-04 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_escalas_options_alter_escolas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalas',
            options={'ordering': ['itinerario'], 'verbose_name': 'Escala', 'verbose_name_plural': 'Escalas'},
        ),
    ]
