# Generated by Django 4.2.5 on 2023-11-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0002_alter_facesverify_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facesprevisaoemocional',
            name='region',
        ),
    ]
