# Generated by Django 4.2.5 on 2023-11-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_fotos_pessoa'),
        ('analytical', '0003_remove_facesprevisaoemocional_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='facesverify',
            name='status',
            field=models.CharField(choices=[('0', 'Analisando'), ('1', 'Auditado'), ('2', 'Rejeitado')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='facesverify',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.pessoas'),
        ),
    ]
