# Generated by Django 4.2.5 on 2023-11-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0004_facesverify_status_alter_facesverify_pessoa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facesverify',
            options={'verbose_name': 'Face Verifica', 'verbose_name_plural': 'Faces Verificadas'},
        ),
    ]
