# Generated by Django 4.2.5 on 2023-11-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0005_alter_facesverify_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facesverify',
            name='status',
            field=models.CharField(choices=[('0', 'Analisada'), ('1', 'Auditada'), ('2', 'Rejeitada')], default='0', max_length=1),
        ),
    ]
