FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

WORKDIR /api

RUN pip install --upgrade pip

COPY ./api/requirements.txt /api/

RUN pip install -r requirements.txt

COPY ./api /api

COPY ./configs/scripts/django_init.sh /api/configs/scripts/django_init.sh

# Utilizar script sh
ENTRYPOINT ["/api/configs/scripts/django_init.sh"]
