FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

WORKDIR /api

RUN pip install --upgrade pip

COPY ./api/requirements.txt /api/

RUN pip install -r requirements.txt

COPY ./api /api

ADD ./configs/scripts/django_init.sh /docker-entrypoint.sh

RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
