FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --upgrade pip

COPY ./app/requirements.txt /app/

RUN pip install -r requirements.txt

COPY ./app/ /app

CMD [ "python", "manage.py", "makemigrations"]

CMD [ "python", "manage.py", "migrate"]

CMD [ "python", "manage.py", "runserver", "port=8000"]
