# Generated by Django 4.2.5 on 2023-10-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashDetectFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detect_count', models.IntegerField(default=0)),
                ('detect_valid', models.IntegerField(default=0)),
                ('detect_by_hour', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dashboard Detect Face',
                'verbose_name_plural': 'Dashboard Detect Face',
            },
        ),
        migrations.CreateModel(
            name='DashVerifyFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verify_count', models.IntegerField(default=0)),
                ('verifyt_sucess', models.IntegerField(default=0)),
                ('verify_by_hour', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dashboard Verify Face',
                'verbose_name_plural': 'Dashboard Verify Face',
            },
        ),
    ]
