# Generated by Django 4.1.9 on 2023-06-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escolas',
            options={'verbose_name_plural': 'Escolas'},
        ),
        migrations.AlterModelOptions(
            name='pessoas',
            options={'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='presencas',
            options={'verbose_name_plural': 'Presencas'},
        ),
    ]
