# Generated by Django 4.2.5 on 2023-09-10 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_aluno_options'),
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenciasEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.aluno')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.locais')),
            ],
            options={
                'verbose_name': 'Frequência Escolar',
                'verbose_name_plural': 'Frequências Escolar',
            },
        ),
        migrations.DeleteModel(
            name='Frequencias',
        ),
    ]
