# Generated by Django 4.2.5 on 2023-09-05 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameras',
            options={'verbose_name': 'Câmera', 'verbose_name_plural': 'Câmeras'},
        ),
        migrations.AlterModelOptions(
            name='locais',
            options={'verbose_name': 'Local', 'verbose_name_plural': 'Locais'},
        ),
        migrations.AlterModelOptions(
            name='notafiscal',
            options={'verbose_name': 'Nota Fiscal', 'verbose_name_plural': 'Notas Fiscais'},
        ),
    ]
