# Generated by Django 4.2.5 on 2023-10-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_alter_processamentos_dia_alter_processamentos_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamentos',
            name='horario',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
