# Generated by Django 4.2.5 on 2023-10-06 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_alter_tarefas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameras',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Processamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.cameras')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
