# Generated by Django 4.2.5 on 2023-10-10 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_cameras_status_processamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processamentos',
            name='payload',
        ),
        migrations.AddField(
            model_name='processamentos',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processamentos',
            name='path',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
