# Generated by Django 4.2.5 on 2023-10-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_remove_processamentos_payload_processamentos_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processamentos',
            options={'ordering': ['id'], 'verbose_name': 'Processamento', 'verbose_name_plural': 'Processamentos'},
        ),
        migrations.AddField(
            model_name='processamentos',
            name='status',
            field=models.CharField(choices=[('Inicializado', 'Inicializado'), ('Cancelado', 'Cancelado'), ('Erro', 'Erro'), ('Enviado', 'Enviado')], default='Inicializado', max_length=20),
        ),
    ]
