# Generated by Django 4.2.5 on 2023-10-22 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_remove_frequenciasescolar_local_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=250, unique=True)),
                ('retry', models.IntegerField(default=0)),
                ('backend_detector', models.CharField(default='mtcnn', max_length=20)),
                ('model_detector', models.CharField(default='hog', max_length=20)),
                ('auditado', models.BooleanField(default=False)),
                ('processamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.processamentos')),
            ],
            options={
                'verbose_name': 'Face Detectada',
                'verbose_name_plural': 'Faces Detectadas',
                'ordering': ['id'],
            },
        ),
    ]
