# Generated by Django 4.2.5 on 2023-10-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_alter_processamentos_options_processamentos_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processamentos',
            name='data',
        ),
    ]
