# Generated by Django 4.2.5 on 2023-10-10 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0007_remove_processamentos_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamentos',
            name='dia',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processamentos',
            name='status',
            field=models.CharField(choices=[('Inicializado', 'Inicializado'), ('Cancelado', 'Cancelado'), ('Erro', 'Erro'), ('Processado', 'Processado')], default='Inicializado', max_length=20),
        ),
    ]
