# Generated by Django 4.2.5 on 2023-10-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0008_alter_processamentos_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processamentos',
            options={'ordering': ['status'], 'verbose_name': 'Processamento', 'verbose_name_plural': 'Processamentos'},
        ),
    ]
