# Generated by Django 4.2.5 on 2023-10-26 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_fotos_pessoa'),
        ('cameras', '0010_rename_path_faces_path_face'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faces',
            options={'ordering': ['id', 'auditado'], 'verbose_name': 'Face Detectada', 'verbose_name_plural': 'Faces Detectadas'},
        ),
        migrations.CreateModel(
            name='FaceVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('auditado', models.BooleanField(default=False)),
                ('model_backend', models.CharField(max_length=100, null=True)),
                ('caminho_do_face', models.CharField(max_length=250)),
                ('detector_backend', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=20)),
                ('metrics', models.CharField(max_length=20)),
                ('data_captura', models.DateField()),
                ('hora_captura', models.CharField(max_length=20)),
                ('captura_base', models.CharField(max_length=250)),
                ('file_dataset', models.CharField(max_length=250)),
                ('verify', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.aluno')),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cameras.cameras')),
            ],
            options={
                'verbose_name': 'Auditado',
                'verbose_name_plural': 'Auditados',
            },
        ),
    ]
