# Generated by Django 4.2.5 on 2023-10-28 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_fotos_pessoa'),
        ('cameras', '0011_alter_faces_options_faceverify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faces',
            name='distance_metric',
        ),
        migrations.RemoveField(
            model_name='faces',
            name='model_detector',
        ),
        migrations.RemoveField(
            model_name='faceverify',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='faceverify',
            name='detector_backend',
        ),
        migrations.RemoveField(
            model_name='faceverify',
            name='metrics',
        ),
        migrations.RemoveField(
            model_name='faceverify',
            name='model_backend',
        ),
        migrations.RemoveField(
            model_name='faceverify',
            name='model_name',
        ),
        migrations.AddField(
            model_name='faceverify',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.pessoas'),
        ),
        migrations.AlterField(
            model_name='processamentos',
            name='status',
            field=models.CharField(choices=[('Criado', 'Criado'), ('Processado', 'Processado'), ('Verificado', 'Verificado'), ('Analisado', 'Analisado'), ('Error', 'Error')], default='Criado', max_length=20),
        ),
    ]
