# Generated by Django 4.2.5 on 2023-10-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0012_remove_faces_distance_metric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamentos',
            name='status',
            field=models.CharField(choices=[('Criado', 'Criado'), ('Processado', 'Processado'), ('Enviado', 'Enviado'), ('Verificado', 'Verificado'), ('Analisado', 'Analisado'), ('Error', 'Error')], default='Criado', max_length=20),
        ),
    ]
