# Generated by Django 4.2.5 on 2023-11-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0013_alter_processamentos_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceVerify',
        ),
    ]
