# Generated by Django 4.2.5 on 2023-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0014_delete_faceverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='faces',
            name='status',
            field=models.CharField(default='Criado', max_length=20, verbose_name=(('Criado', 'Criado'), ('Processado', 'Processado'), ('Error', 'Error'))),
        ),
        migrations.AlterField(
            model_name='processamentos',
            name='status',
            field=models.CharField(choices=[('Criado', 'Criado'), ('Processado', 'Processado'), ('Error', 'Error')], default='Criado', max_length=20),
        ),
    ]
