# Generated by Django 4.2.5 on 2023-11-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0019_rename_aluno_frequenciasescolar_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faces',
            name='path_face',
            field=models.CharField(max_length=350, unique=True),
        ),
    ]
