# Generated by Django 4.2.5 on 2023-11-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0020_alter_faces_path_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faces',
            name='auditado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
