# Generated by Django 4.2.7 on 2023-11-22 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0021_alter_faces_auditado'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequenciasescolar',
            name='horario',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
