# Generated by Django 4.2.5 on 2023-09-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turmas',
            options={'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='perfil',
            field=models.CharField(choices=[('Tutor', 'Tutor'), ('Colaborador', 'Colaborador'), ('Estudante', 'Estudante')], max_length=11),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outros', 'Outros')], max_length=10),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='periodo',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Outros', 'Outros')], max_length=10),
        ),
    ]
