# Generated by Django 4.2.5 on 2023-09-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_turmas_options_alter_pessoas_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turmas',
            name='periodo',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Outros', 'Outros')], max_length=10),
        ),
    ]
