# Generated by Django 4.2.5 on 2023-09-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_turmas_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='cadastros.turmas', verbose_name='turma'),
        ),
    ]
