# Generated by Django 4.2.5 on 2023-09-10 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_pessoas_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoas',
            name='turma',
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.pessoas')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.turmas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='turmas',
            name='alunos',
            field=models.ManyToManyField(through='cadastros.Aluno', to='cadastros.pessoas'),
        ),
    ]
