# Generated by Django 4.2.5 on 2023-09-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_remove_pessoas_turma_aluno_turmas_alunos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Alunos', 'verbose_name_plural': 'Alunos'},
        ),
    ]
