# Generated by Django 4.2.5 on 2023-11-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0006_alter_facesverify_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facesprevisaoemocional',
            name='face',
        ),
    ]
