# Generated by Django 4.2.5 on 2023-11-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0007_remove_facesprevisaoemocional_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facesprevisaoemocional',
            name='auditado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
