# Generated by Django 4.2.4 on 2023-08-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_escolas_options_alter_pessoas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='ra',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
