# Generated by Django 4.2.4 on 2023-08-31 04:35

import core.cadastros.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_pessoas_ra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto1', models.ImageField(upload_to=core.cadastros.models.Fotos.get_upload_path)),
                ('foto2', models.ImageField(upload_to=core.cadastros.models.Fotos.get_upload_path)),
                ('foto3', models.ImageField(upload_to=core.cadastros.models.Fotos.get_upload_path)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.pessoas')),
            ],
            options={
                'verbose_name_plural': 'Fotos',
            },
        ),
    ]
