# Generated by Django 4.2.5 on 2023-10-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_alter_processamentos_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamentos',
            name='retry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='processamentos',
            name='status',
            field=models.CharField(choices=[('Criado', 'Criado'), ('Cancelado', 'Cancelado'), ('Pendente', 'Pendente'), ('Erro', 'Erro'), ('Processado', 'Processado')], default='Criado', max_length=20),
        ),
    ]
