# Generated by Django 4.2.5 on 2023-10-22 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_processamentos_retry_alter_processamentos_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequenciasescolar',
            name='local',
        ),
        migrations.AddField(
            model_name='frequenciasescolar',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cameras.cameras'),
        ),
        migrations.AlterField(
            model_name='processamentos',
            name='path',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
