# Generated by Django 4.2.5 on 2023-10-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_faces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faces',
            name='retry',
        ),
        migrations.AddField(
            model_name='faces',
            name='distance_metric',
            field=models.CharField(default='euclidean_l2', max_length=20),
        ),
        migrations.AlterField(
            model_name='faces',
            name='backend_detector',
            field=models.CharField(default='retinaface', max_length=20),
        ),
        migrations.AlterField(
            model_name='faces',
            name='model_detector',
            field=models.CharField(default='Facenet', max_length=20),
        ),
    ]
