# Generated by Django 4.2.5 on 2023-10-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0007_remove_faces_retry_faces_distance_metric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamentos',
            name='status',
            field=models.CharField(choices=[('Criado', 'Criado'), ('Processado', 'Processado'), ('Verificado', 'Verificado'), ('Error', 'Error')], default='Criado', max_length=20),
        ),
    ]
