# Generated by Django 4.2.5 on 2023-11-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0015_faces_status_alter_processamentos_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faces',
            options={'ordering': ['status', 'auditado'], 'verbose_name': 'Face Detectada', 'verbose_name_plural': 'Faces Detectadas'},
        ),
        migrations.AlterField(
            model_name='faces',
            name='status',
            field=models.CharField(choices=[('Criado', 'Criado'), ('Processado', 'Processado'), ('Error', 'Error')], default='Criado', max_length=20),
        ),
    ]
