# Generated by Django 4.2.5 on 2023-11-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0016_alter_faces_options_alter_faces_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faces',
            name='status',
            field=models.CharField(blank=True, choices=[('Criado', 'Criado'), ('Processado', 'Processado'), ('Error', 'Error')], default='Criado', max_length=20, null=True),
        ),
    ]
