# Generated by Django 4.2.5 on 2023-11-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0018_alter_frequenciasescolar_aluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequenciasescolar',
            old_name='aluno',
            new_name='pessoa',
        ),
    ]
